---
title: "Model_1"
author: "Srivastav Budugutta"
date: "2023-03-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#initiating library

```{r}

library(tidyverse)
```
## Function definitions
```{r}
clean_rating = function(dat){
  dat = dat %>% mutate(rating = if_else(rating<0,0,rating))
  
  return(dat)
}
change_track_explicit_to_numeric = function(dat){
  dat = dat %>% mutate(track_explicit = ifelse(track_explicit == FALSE,0,1))
  return(dat)
}


```


```{r}
songs = read_csv("data/analysisData.csv")

songs = clean_rating(songs)
songs = change_track_explicit_to_numeric(songs)
songs$track_explicit
head(songs)
min(songs$rating)
# geners_modify = songs %>% mutate(genre = str_extract_all(genre, regex("\'(.*?)\'", ignore_case = T)))
# geners_modify$genre

# we are trying to separate all the genre types
geners_modify = songs %>% separate_rows(genre, sep = ",\\s*")
geners_modify = geners_modify %>%  mutate(genre = str_replace_all(genre, "\\[|\\]|'|\"", ""))
geners_modify %>% group_by(genre) %>% count() %>% filter(n==1)
genre_mean_rating = geners_modify %>% group_by(genre) %>% summarize(avg_rating = mean(rating))
genre_mean_rating %>% filter(genre == "acoustic punk")
genre_mean_rating[geners_modify$genre,]
head(geners_modify)
geners_modify = geners_modify %>% mutate(track_duration = track_duration/(60*1000))

(geners_modify %>% group_by(genre) %>% summarize(avg_rating = mean(rating)) %>% arrange(avg_rating))
# geners_modify_1= geners_modify %>% group_by(genre) %>% summarize(avg_rating = mean(rating)) %>% ungroup() %>% mutate(genre = avg_rating)
# now we know what are the mean ratings for each genre now we will combine it to the song id.
geners_modify_1= geners_modify %>% group_by(genre) %>% mutate(avg_rating = mean(rating)) %>% ungroup() %>% mutate(genre = avg_rating)
geners_modify_1 = geners_modify_1 %>% group_by(id) %>% mutate(genre = mean(genre))
geners_modify_1 = geners_modify_1 %>%  select(-avg_rating)
mean(geners_modify_1$genre[c(1:4)])
geners_modify_1 %>% group_by(id)
geners_modify_2= distinct(geners_modify_1, .keep_all = T)
geners_modify_2
```

## Test





```{r}
songs_test = read_csv("data/scoringData.csv")
songs_test = change_track_explicit_to_numeric(songs_test)
songs_test = songs_test %>% separate_rows(genre, sep = ",\\s*")
songs_test = songs_test %>%  mutate(genre = str_replace_all(genre, "\\[|\\]|'|\"", ""))
songs_test = songs_test %>% mutate(track_duration = track_duration/(60*1000))

# songs_test_without_rating = songs_test
genre_mean_rating 
songs_test
songs_test %>% filter(id == "31357")
# genre_mean_rating %>% filter( == "gospel singers")
which.min(genre_mean_rating$avg_rating)
genre_mean_rating[618,]

# copying the corresponding values of the genre type to songs
index_value = match(songs_test$genre, genre_mean_rating$genre)
index_value
songs_test$genre = genre_mean_rating$avg_rating[index_value] 
songs_test_1 = songs_test %>% group_by(id) %>% mutate(genre = mean(genre))
songs_test_1
songs_test_2= distinct(songs_test_1, .keep_all = T)
songs_test_2
dim(songs_test_2)

# merged_song_set = merge(songs_test, genre_mean_rating, by.x = "genre", by.y = "genre",all.x = T)
# merged_song_set
# songs_test$genre = merged_song_set$avg_rating
# songs_test
# songs_test_without_rating
#lets verify if the values for that particular song is given right average rating value.
# songs_test = songs_test %>% group_by(genre) %>% mutate(avg_rating = mean(rating)) %>% ungroup() %>% mutate(genre = avg_rating)
geners_modify_2

model_1 = lm(rating~tempo+time_signature+mode+speechiness+ track_explicit+genre+track_duration+danceability+energy+key+loudness,geners_modify_2)
model_1_predict = predict(model_1,songs_test_2)
length(songs_test_2$id)
length(model_1_predict)
songs_test_2 %>% filter(id == "31357")

songs_test_2[,6]
model_1_predict[c(1:length(model_1_predict))]
mean(model_1_predict)

# if (any(is.na(model_1_predict))) {
#   # Impute missing values with mean
#   mean_predicted_value <- mean(model_1_predict, na.rm = TRUE)
#   model_1_predict[is.na(model_1_predict)] <- mean_predicted_value
# }
mean(model_1_predict)
submissionFile = data.frame(id = songs_test_2$id, rating = model_1_predict)


# submissionFile[is.na(submissionFile)] = 24
write.csv(submissionFile, 'model_2.csv',row.names = F)
head(songs_test)
head(geners_modify)
dim(geners_modify)


```




```{r}



```




```{r}



```




```{r}



```




```{r}



```




```{r}



```