---
title: "Model_2"
author: "Srivastav Budugutta"
date: "2023-03-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Model Overview
>In this we will be investigating on the performers data.
Different types of performers are: individual names, performers with "featuring in between performers, & is there between performers, "+" is there when the artisits combine with other performers.


#initiating library

```{r}

library(tidyverse)
```
## Function definitions
```{r}
clean_rating = function(dat){
  dat = dat %>% mutate(rating = if_else(rating<0,0,rating))
  
  return(dat)
}

change_track_explicit_to_numeric = function(dat){
  dat = dat %>% mutate(track_explicit = ifelse(track_explicit == FALSE,0,1))
  return(dat)
}

create_interactions_Variable = function(dat){
  dat = dat %>% mutate(interactive = danceability*energy)
  return(dat)
}

create_song_intensity = function(dat){
  dat = dat %>% mutate(song_intensity = danceability * energy * (10^(loudness/20)))
  return(dat)
}




```


```{r}
songs = read_csv("data/analysisData.csv")


dim(songs)
songs = clean_rating(songs)
songs = change_track_explicit_to_numeric(songs)
songs %>% group_by(performer) %>% summarise(mean_rating = mean(rating))


# songs$track_explicit
head(songs)
min(songs$rating)

# we are trying to separate all the genre types
geners_modify = songs 
geners_modify = geners_modify %>% mutate(track_duration = track_duration/(60*1000))

(geners_modify %>% group_by(genre) %>% summarize(avg_rating = mean(rating)) %>% arrange(avg_rating))


geners_modify_2 = create_interactions_Variable(geners_modify)
geners_modify_2 = create_song_intensity(geners_modify_2)
geners_modify_2
```

## Test





```{r}
songs_test = read_csv("data/scoringData.csv")
songs_test = change_track_explicit_to_numeric(songs_test)
songs_test = songs_test %>% mutate(track_duration = track_duration/(60*1000))

songs_test_2 = create_interactions_Variable(songs_test)
songs_test_2 = create_song_intensity(songs_test_2)
dim(songs_test_2)


geners_modify_2

model_1 = lm(rating~tempo+time_signature+mode+speechiness+ track_explicit+track_duration+danceability+energy+key+loudness+ interactive+song_intensity,geners_modify_2)
model_1_predict = predict(model_1,songs_test_2)
length(songs_test_2$id)
length(model_1_predict)
songs_test_2[2812,]

songs_test_2[,6]

submissionFile = data.frame(id = songs_test_2$id, rating = model_1_predict)
submissionFile[is.na(submissionFile)] = 24
write.csv(submissionFile, 'model_7.csv',row.names = F)
head(songs_test)
head(geners_modify)
dim(geners_modify)


```




```{r}



```




```{r}



```




```{r}



```




```{r}



```




```{r}



```